### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by theo-bnts** [theo-bnts/custom-maker#1]
The following list represents what can be done to improve the bot.
Feel free to add to it by commenting!

- [ ] Rewrite the `*pass` command
- [ ] Rewrite the `*replay` command with the [new replay parser](https://github.com/ThisNils/node-replay-reader) (by @ThisNils)
- [ ] Replace all `needle` and `request-promise` requests with `axios`
- [ ] Finish translating the various commands
- [ ] Change to Discord.JS v13.X.X
➥ Support slashs commands

**Comment by Artforlfmj** [comment]
For replay command do not use axios. It corrupts files. Consider keeping needle for that command

**Comment by allan-zupcic** [comment]
I also suggest adding the slash commands to the bot

**Comment by ghost** [comment]
I am planning on doing that too
